In [1]:
#Importing the Python libraries and packages
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report


In [15]:
# Including the CSV file using pandas
cars = pd.read_csv("attachment_mtcars.csv")


In [16]:
cars.head()

car_model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [4]:
cars.shape

(32, 12)

In [ ]:
# Checking for NUll or NaN values in the file
cars.isnull().sum()

In [10]:
#car is automatic or Manual   'am' as my target/dependent/y
# Using predictor variables/ features/ independent variabes, x1, x2, x3,... => X
# X rep 'mpg' mileage of the car, 'hp' horse power of the car, 'wt' weight of the car
y = cars.am
X = cars.loc[:,['mpg','hp','wt']]

In [8]:
# model used for prediction is Logistic Regression Logit model
model_logr = LogisticRegression()

In [12]:
# Classifing as Trianing and Test set of data, 70 % training data set, 30 % test Data set
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.3,random_state=10)

In [13]:
X_train.shape

(22, 3)

In [14]:
X_test.shape

(10, 3)

In [15]:
# Fitting the X and y trining data set to train the model
model_logr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [16]:
# Testing the remaining data by using Xtest from the trained data set
y_predict = model_logr.predict(X_test)

In [17]:
y_predict

array([1, 0, 0, 1, 0, 0, 0, 1, 0, 1])

In [18]:
y_test

20    0
7     0
5     0
2     1
3     0
21    0
13    0
28    1
12    0
1     1
Name: am, dtype: int64

In [20]:
print(classification_report(y_test,y_predict))

             precision    recall  f1-score   support

          0       1.00      0.86      0.92         7
          1       0.75      1.00      0.86         3

avg / total       0.93      0.90      0.90        10



In [21]:
from sklearn.metrics import confusion_matrix

In [22]:
# Accuracy of the prediction measured in Confusion matrix
confusion_matrix(y_test,y_predict)

array([[6, 1],
       [0, 3]])

In [105]:
confusion_matrix(y_test2,y_predict2)

array([[5, 1],
       [0, 3]])